export const MAIN_PG_ROUTE = '/'
export const HOME_PG_ROUTE = '/home'
export const SETTINGS_PG_ROUTE = '/settings'
export const NOTE_PG_ROUTE = '/note'
export const LOGIN_ROUTE = '/auth/login'
export const REGISTRATION_ROUTE = '/auth/registration'
export const AUTH_PG_ROUTE = '/auth'
export const NOTFOUND_PG_ROUTE = '/404'